#!/usr/bin/env python3
import argparse
import csv
import math
from datetime import datetime, timezone
from pathlib import Path

import matplotlib.pyplot as plt


def parse_args():
    parser = argparse.ArgumentParser(description="生成 Fig.3(a) 的 TikZ 图")
    parser.add_argument("--input", default="raw_data/costs.csv")
    parser.add_argument("--output", default="plots/fig3a.tex")
    parser.add_argument("--png-output", default="plots/fig3a.png")
    parser.add_argument("--summary", default="raw_data/costs_summary.csv")
    return parser.parse_args()


def load_rows(path: Path):
    rows = []
    with path.open("r", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            row["gas_used"] = float(row["gas_used"])
            rows.append(row)
    return rows


def percentile(values, p):
    if not values:
        return 0.0
    values = sorted(values)
    k = (len(values) - 1) * p
    f = math.floor(k)
    c = math.ceil(k)
    if f == c:
        return values[int(k)]
    d0 = values[f] * (c - k)
    d1 = values[c] * (k - f)
    return d0 + d1


def summarize(rows):
    buckets = {}
    for row in rows:
        key = (row["architecture"], row["phase"])
        buckets.setdefault(key, []).append(row["gas_used"])

    summary = []
    for (architecture, phase), values in sorted(buckets.items()):
        summary.append(
            {
                "architecture": architecture,
                "phase": phase,
                "n": len(values),
                "median_gas": percentile(values, 0.5),
                "p10_gas": percentile(values, 0.1),
                "p90_gas": percentile(values, 0.9),
            }
        )
    return summary


def write_summary(summary, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "architecture",
                "phase",
                "n",
                "median_gas",
                "p10_gas",
                "p90_gas",
            ],
        )
        writer.writeheader()
        writer.writerows(summary)


def build_tikz(summary, output_path: Path):
    phases = ["identity", "session", "settlement"]
    phase_labels = {
        "identity": "Identity",
        "session": "Session",
        "settlement": "Settlement",
    }
    architectures = ["web3_conventional", "agent_osi_single"]
    label_map = {
        "web3_conventional": "Web3 Baseline",
        "agent_osi_single": "Agent-OSI",
    }

    lookup = {(item["architecture"], item["phase"]): item for item in summary}
    data = {arch: [] for arch in architectures}
    for arch in architectures:
        for phase in phases:
            item = lookup.get((arch, phase))
            median = (item["median_gas"] / 1000) if item else 0.0
            data[arch].append(median)

    web3_total = sum(data["web3_conventional"][1:])
    osi_total = sum(data["agent_osi_single"][1:])
    savings = (1 - osi_total / web3_total) * 100 if web3_total else 0.0

    coords = {
        arch: " ".join(
            f"({phase_labels[phase]},{value:.3f})"
            for phase, value in zip(phases, data[arch])
        )
        for arch in architectures
    }

    caption = (
        "Fig. 3: Performance evaluation of the Agent-OSI prototype. (a) Cost: on-chain "
        "cost per completed session under different interaction patterns and baselines. "
        "Web2 baseline has zero on-chain cost (off-chain billing) and is omitted. "
        "Gas values are EVM execution costs (network fee excluded)."
    )

    tikz = f"""% Auto-generated by cost.py
\\begin{{figure}}[t]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[
  ybar,
  bar width=9pt,
  width=8.6cm,
  height=4.6cm,
  symbolic x coords={{{",".join(phase_labels[p] for p in phases)}}},
  xtick=data,
  ylabel={{On-chain cost (k gas)}},
  legend style={{at={{(0.5,1.05)}},anchor=south,legend columns=-1}},
  ymin=0,
  ymajorgrids,
  grid style={{dashed,gray!30}},
  tick label style={{font=\\footnotesize}},
  label style={{font=\\footnotesize}},
  legend style={{font=\\footnotesize}},
]
\\addplot+[fill={{rgb,255:red,215;green,124;blue,90}}] coordinates {{{coords["web3_conventional"]}}};
\\addplot+[fill={{rgb,255:red,76;green,139;blue,184}}] coordinates {{{coords["agent_osi_single"]}}};
\\legend{{{label_map["web3_conventional"]}, {label_map["agent_osi_single"]}}}
\\node[anchor=west,font=\\footnotesize] at (rel axis cs:0.02,0.95) {{Savings {savings:.1f}\\%}};
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{{caption}}}
\\end{{figure}}
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(tikz, encoding="utf-8")

    meta = {"generated_at": datetime.now(timezone.utc).isoformat()}
    meta_path = output_path.parent / "fig3a_meta.json"
    meta_path.write_text(json_dump(meta), encoding="utf-8")


def build_png(summary, output_path: Path):
    phases = ["identity", "session", "settlement"]
    phase_labels = {
        "identity": "Identity",
        "session": "Session",
        "settlement": "Settlement",
    }
    architectures = ["web3_conventional", "agent_osi_single"]
    label_map = {"web3_conventional": "Web3 Baseline", "agent_osi_single": "Agent-OSI"}
    colors = {"web3_conventional": "#D77C5A", "agent_osi_single": "#4C8BB8"}

    lookup = {(item["architecture"], item["phase"]): item for item in summary}
    data = []
    lower = []
    upper = []
    for arch in architectures:
        medians = []
        lows = []
        highs = []
        for phase in phases:
            item = lookup.get((arch, phase))
            median = (item["median_gas"] / 1000) if item else 0.0
            p10 = (item["p10_gas"] / 1000) if item else 0.0
            p90 = (item["p90_gas"] / 1000) if item else 0.0
            medians.append(median)
            lows.append(max(median - p10, 0))
            highs.append(max(p90 - median, 0))
        data.append(medians)
        lower.append(lows)
        upper.append(highs)

    x = range(len(phases))
    width = 0.32
    fig, ax = plt.subplots(figsize=(7.6, 4.2))
    for idx, arch in enumerate(architectures):
        positions = [i + (idx - 0.5) * width for i in x]
        ax.bar(
            positions,
            data[idx],
            width,
            label=label_map[arch],
            color=colors[arch],
        )
        ax.errorbar(
            positions,
            data[idx],
            yerr=[lower[idx], upper[idx]],
            fmt="none",
            ecolor="#333333",
            elinewidth=1,
            capsize=3,
        )

    web3_total = sum(data[0][1:])
    osi_total = sum(data[1][1:])
    if web3_total > 0:
        savings = (1 - osi_total / web3_total) * 100
        ax.text(
            0.02,
            0.95,
            f"Savings {savings:.1f}%",
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=10,
        )

    ax.set_ylabel("On-chain cost (k gas)")
    ax.set_xticks(list(x))
    ax.set_xticklabels([phase_labels[p] for p in phases])
    ax.legend(frameon=False, fontsize=9)
    ax.grid(axis="y", linestyle="--", alpha=0.4)
    fig.tight_layout()

    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=300)


def json_dump(payload):
    import json

    return json.dumps(payload, ensure_ascii=False, indent=2)


def main():
    args = parse_args()
    root = Path(__file__).resolve().parents[1]
    input_path = root / args.input
    output_path = root / args.output
    summary_path = root / args.summary

    rows = load_rows(input_path)
    summary = summarize(rows)
    write_summary(summary, summary_path)
    build_tikz(summary, output_path)
    build_png(summary, root / args.png_output)


if __name__ == "__main__":
    main()
